//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YYBusService04.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class trip
    {
        public trip()
        {
            this.tripStops = new HashSet<tripStop>();
        }
        
        [ScaffoldColumn(false)]
        public int tripId { get; set; }
       
        [ScaffoldColumn(false)]
        [Display(Name="Start Time")]
        public int routeScheduleId { get; set; }
        
        [Required]
        public System.DateTime tripDate { get; set; }
        
        [ScaffoldColumn(false)]
        [Display(Name="Driver")]
        public int driverId { get; set; }
        
        [Required]
        [ScaffoldColumn(false)]
        [Display(Name = "Bus #")]
        public int busId { get; set; }
        
        [Required]
        [StringLength(200)]
        [DataType(DataType.MultilineText)]
        public string comments { get; set; }
    
        public virtual bus bus { get; set; }
        public virtual driver driver { get; set; }
        public virtual routeSchedule routeSchedule { get; set; }
        public virtual ICollection<tripStop> tripStops { get; set; }
    }
}
